// Generated by CoffeeScript 1.12.4
(function() {
  var Lexer;

  exports.Lexer = Lexer = (function() {
    function Lexer() {}

    Lexer.prototype.tokenize = function(code, opts) {
      if (opts == null) {
        opts = {};
      }
      return this.indent = 0;
    };

    return Lexer;

  })();

}).call(this);
