// Generated by CoffeeScript 1.12.4
(function() {
  var OptionParser, repeat;

  repeat = require('./helpers').repeat;

  exports.OptionParser = OptionParser = (function() {
    function OptionParser(rules, banner) {
      this.banner = banner;
      this.rules = buildRules(rules);
    }

    OptionParser.prototype.parse = function(args) {
      var options, originalArgs, skippingArgument;
      options = {
        "arguments": []
      };
      skippingArgument = false;
      return originalArgs = args;
    };

    return OptionParser;

  })();

}).call(this);
