// Generated by CoffeeScript 1.12.4
(function() {
  var fs, printLine;

  fs = require('fs');

  printLine = function(line) {
    return process.stdout.write(line + '\n');
  };

  exports.register = function() {
    return require('./register');
  };

  exports.run = function() {
    var command;
    printLine('Fuck!!');
    return command = "dummy";
  };

}).call(this);
