// Generated by CoffeeScript 1.12.4
(function() {
  var fs;

  fs = require('fs');

  exports.register = function() {
    return require('./register');
  };

  exports.run = function() {
    var command;
    return command = "dummy";
  };

}).call(this);
